title: "Isaac Hua – Data Scientist"
baseurl: ""
url: "https://isaachuahy.github.io"
plugins:
  - jekyll-feed
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title.html
theme: jekyll-theme-minima
