# _config.yml
title: "Isaac Hua – Data Scientist"
baseurl: ""              # blank if USER.github.io
url: "https://isaachuahy.github.io"

# No gems needed—GitHub Pages will auto‑enable jekyll-feed
plugins:
  - jekyll-feed

# Ensure Markdown posts get output under /blog/
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title.html